config/routes.rb
require 'resque/server'

Pugwarriors::Application.routes.draw do
  resources :authentications
  resources :games
  resources :tweets
  resources :comments

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  if ENV["RESQUE_WEB_PASS"]
    Resque::Server.use Rack::Auth::Basic do |username, password|
      password = ENV["RESQUE_WEB_PASS"]
    end
  end

  mount Resque::Server.new, :at => "/resque"

  mount Foundation::Icons::Rails::Engine => '/fi'
  match '/users/signout' => 'sessions#destroy', :as => :signout
  match '/games/:id/join' => 'games#join'
  match '/games/:id/leave' => 'games#leave'
  match '/games/:id/admin' => 'games#admin'
  match '/users/:id/games' => 'users#games'
  match '/games/:id/comments' => 'comments#create'
  match '/games/filter' => 'games#filter'
  match '/tweets/filter' => 'tweets#filter'
  match '/application/viewed_notification' => 'application#viewed_notification'
  match '/tweets/get_new_tweets' => 'tweets#get_new_tweets'
  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/authentication.rb
class Authentication
  include Mongoid::Document
  field :user_id, type: Integer
  field :provider, type: String
  field :uid, type: String

  belongs_to :user
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  # GET /authentications
  # GET /authentications.json
  def index
    @authentications = current_user.authentications if current_user

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @authentications }
    end
  end

  # GET /authentications/1
  # GET /authentications/1.json
  def show
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/new
  # GET /authentications/new.json
  def new
    @authentication = Authentication.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @authentication }
    end
  end

  # GET /authentications/1/edit
  def edit
    @authentication = Authentication.find(params[:id])
  end

  # POST /authentications
  # POST /authentications.json
  def create
    omniauth = request.env["omniauth.auth"]
    authentication = Authentication.where(:provider => omniauth['provider'], :uid => omniauth['uid']).first
    session[:token] = omniauth['credentials']['token']
    session[:secret] = omniauth['credentials']['secret']
    if authentication
      flash[:notice] = t(:signed_in)
      if user = User.where({:handle => omniauth['info']['nickname']}).first
        user.apply_omniauth(omniauth)
        user.save
      end
      sign_in_and_redirect(:user, authentication.user)
    elsif current_user
      current_user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      @current_user.apply_omniauth(omniauth)
      @current_user.save
      flash[:notice] = t(:success)
      redirect_to authentications_url
    elsif user = create_new_omniauth_user(omniauth)
      user.authentications.create!(:provider => omniauth['provider'], :uid => omniauth['uid'])
      flash[:notice] = t(:welcome)
      sign_in_and_redirect(:user, user)
    else
      flash[:alert] = t(:fail)
      redirect_to new_user_registration_url
    end
  end

  # PUT /authentications/1
  # PUT /authentications/1.json
  def update
    @authentication = Authentication.find(params[:id])

    respond_to do |format|
      if @authentication.update_attributes(params[:authentication])
        format.html { redirect_to @authentication, notice: 'Authentication was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @authentication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authentications/1
  # DELETE /authentications/1.json
  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = t(:successfully_destroyed_authentication)
    redirect_to authentications_url
  end

  def create_new_omniauth_user(omniauth)
    user = User.new
    user.apply_omniauth(omniauth)
    if user.save
      user
    else
      nil
    end
  end
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/views/authentications/_form.html.erb
<div class="large-12 columns">
  <div class="row">
    <%= form_for(@authentication) do |f| %>
      <% if @authentication.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@authentication.errors.count, "error") %> prohibited this authentication from being saved:</h2>

          <ul>
            <% @authentication.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="large-12 columns">
        <%= f.label :user_id %><br />
        <%= f.number_field :user_id %>
      </div>
      <div class="large-12 columns">
        <%= f.label :provider %><br />
        <%= f.text_field :provider %>
      </div>
      <div class="large-12 columns">
        <%= f.label :uid %><br />
        <%= f.text_field :uid %>
      </div>
      <div class="large-12 columns">
        <%= f.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/authentications/edit.html.erb
<h1>Editing authentication</h1>

<%= render 'form' %>

<%= link_to 'Show', @authentication %> |
<%= link_to 'Back', authentications_path %>

app/views/authentications/index.html.erb
<h1>Listing authentications</h1>

<table>
  <tr>
    <th>User</th>
    <th>Provider</th>
    <th>Uid</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @authentications.each do |authentication| %>
  <tr>
    <td><%= authentication.user_id %></td>
    <td><%= authentication.provider %></td>
    <td><%= authentication.uid %></td>
    <td><%= link_to 'Show', authentication %></td>
    <td><%= link_to 'Edit', edit_authentication_path(authentication) %></td>
    <td><%= link_to 'Destroy', authentication, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Authentication', new_authentication_path %>

app/views/authentications/new.html.erb
<h1>New authentication</h1>

<%= render 'form' %>

<%= link_to 'Back', authentications_path %>

app/views/authentications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @authentication.user_id %>
</p>

<p>
  <b>Provider:</b>
  <%= @authentication.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @authentication.uid %>
</p>


<%= link_to 'Edit', edit_authentication_path(@authentication) %> |
<%= link_to 'Back', authentications_path %>