config/routes.rb
require 'resque/server'

Pugwarriors::Application.routes.draw do
  resources :authentications
  resources :games
  resources :tweets
  resources :comments

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  if ENV["RESQUE_WEB_PASS"]
    Resque::Server.use Rack::Auth::Basic do |username, password|
      password = ENV["RESQUE_WEB_PASS"]
    end
  end

  mount Resque::Server.new, :at => "/resque"

  mount Foundation::Icons::Rails::Engine => '/fi'
  match '/users/signout' => 'sessions#destroy', :as => :signout
  match '/games/:id/join' => 'games#join'
  match '/games/:id/leave' => 'games#leave'
  match '/games/:id/admin' => 'games#admin'
  match '/users/:id/games' => 'users#games'
  match '/games/:id/comments' => 'comments#create'
  match '/games/filter' => 'games#filter'
  match '/tweets/filter' => 'tweets#filter'
  match '/application/viewed_notification' => 'application#viewed_notification'
  match '/tweets/get_new_tweets' => 'tweets#get_new_tweets'
  match '/auth/:provider/callback' => 'authentications#create'
end

app/models/game.rb
class Game
  include Mongoid::Document

  field :name, type: String
  field :game_type, type: String
  field :location, type: String
  field :city, type: String
  field :state, type: String
  field :zip, type: String
  field :date, type: Date
  field :time, type: String
  field :player_max, type: String
  field :equipment, type: String
  field :coordinates, type: Array
  field :place_id, type: Integer
  field :tweet_text, type: String
  field :admin, type: Integer
  field :author_handle, type: String
  field :author_image, type: String

  has_many :tweets
  has_many :comments
  has_and_belongs_to_many :users

  validates_presence_of :name, :zip, :city, :state, :date, :game_type, :time
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = Game.all.order_by([:date, :desc])
    @games.each do |game|
      if game.admin
        user = User.where({'twitter_id' => game.admin}).first
        game.author_handle = user.handle
        game.author_image = user.image
        game.save
      end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
      format.js { render :js => @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = Game.find(params[:id])
    @comment = Comment.new
    @comments = @game.comments.order_by([:date_time, :desc])
    w_api = Wunderground.new('fdb34ff48699837d')
    @weather = w_api.planner_for(@game.date, @game.date, @game.zip)
    # Variables for use inside of application.js
    gon.lat = @game.coordinates[0]
    gon.long = @game.coordinates[1]
    gon.location_marker = '../assets/icons/location-marker.png'
    if @game.admin
      @user = User.where({ 'twitter_id' => @game.admin }).first
    end
    @users = @game.users
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = Game.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    session[:return_to] ||= request.referer
    @game = Game.find(params[:id])
  end

  # POST /games
  # POST /games.json
  def create
    date = params[:game][:date].split('/')
    @game = Game.new(params[:game])
    @game.date = date[2] + '-' + date[0] + '-' + date[1]
    location_string = ''
    if @game[:location]
      location_string = @game[:location] if @game[:location]
      coordinates = Geocoder.coordinates(location_string)
      @game.coordinates = coordinates unless coordinates.nil?
    end
    if @game[:game_type]
      @game.tweet_text = 'Want to play some ' + @game[:game_type] + '? Meet me at ' + @game[:location] + ', ' + @game[:time] + ' on ' + @game[:date].to_s
    end
    if current_user
      @game.admin = @current_user.twitter_id
    end
    respond_to do |format|
      if @game.save
        if current_user
          add_user_to_game
          @game.admin = current_user.twitter_id
          @game.save
        end
        if ENV["TWITTER_POSTS_ENABLED"] == "TRUE"
          twitter = getTwitterClient
          game = params[:game]
          lat = @game.coordinates ? nil : coordinates[0]
          long = game.coordinates ? nil : coordinates[1]
          text = @game.tweet_text
          tweet = twitter.update(text, {:lat => lat, :long => long})
          @game.tweet_id = tweet[:id]
          @current_user.tweet_id = tweet[:id]
          @game.save
        end
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = Game.find(params[:id])

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to session.delete(:return_to), notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end

  def join
    if current_user
      @game = Game.find(params[:id])
      joined_notification
      respond_to do |format|
        if add_user_to_game
          format.html { redirect_to @game, notice: 'Joined game.'}
          format.json { render json: @game }
          format.js
        else
          format.html { redirect_to @game, notice: 'Unable to join game.'}
          format.json { render json: @game }
          format.js
        end
      end
    else
      session["user_return_to"] = request.url
      redirect_to '/auth/twitter'
    end
  end

  def leave
    if current_user
      @game = Game.find(params[:id])
      leave_notification
      respond_to do |format|
        if remove_user_from_game
          format.html { redirect_to @game, notice: 'Left game.'}
          format.json { render json: @game }
          format.js
        else
          format.html { redirect_to @game, notice: 'You have to go to the game brah.'}
          format.json { render json: @game}
          format.js
        end
      end
    end
  end

  def filter
    @filter = params[:games_filter][:zip] ? params[:games_filter][:zip] : nil
    coordinates = Geocoder.coordinates(@filter)
    all_games = Game.all
    games = []

    all_games.each do |game|
      if coordinates
        distance = Geocoder::Calculations.distance_between(coordinates, game.coordinates)
        if distance <= 30
          games << game.id
        end
      end
    end
    @games = Game.any_in(:_id => games)
    @games = all_games if @filter.nil? || @filter == ''

    render :index
  end

  private
  def add_user_to_game
    @game.users.push(@current_user)
  end

  def remove_user_from_game
    @game.users.delete(@current_user)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<div id="create-game" class="large-12 columns">
  <%= form_for(@game) do |f| %>
    <% if @game.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>
        <ul>
          <% @game.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div id="tweet-information" class="large-12 columns">
      <div class="row">
        <h4 class="clearfix">
          <div class="row">
            <div class="large-12 columns">
              <div class="row">
                <div class="tweet-text-sections large-5 columns"><label>I want to play a pick-up game of</label></div>
                <div class="large-7 columns"><%= f.text_field(:game_type, :placeholder => "What kind of game?") %></div>
              </div>
            </div>
            <div class="large-12 columns">
              <div class="row">
                <div class="tweet-text-sections large-2 columns"><label>Meet me at</label></div>
                <div class="large-4 columns"><%= f.text_field(:location, :placeholder => "Address or place...") %></div>
                <div class="tweet-text-sections large-1 columns"><label> at,</label></div>
                <div class="large-2 columns"><%= f.text_field(:time, :placeholder => "What time?") %></div>
                <div class="tweet-text-sections large-1 columns"><label>on, </label></div>
                <div class="large-2 columns"><%= f.datepicker 'date', :class => 'datePicker', :placeholder => "What date?" %></div>
              </div>
            </div>
          </div>
        </h4>
        <%= link_to "Next", '#', :class => 'button right next-button' %>
      </div>
    </div>
    <div id="additional-information">
      <div class="row">
        <div class="large-12 columns">
          <div class="row">
            <div class="large-12 columns">
              <%= f.label(:name, "Game title") %>
              <%= f.text_field(:name, :placeholder => "Enter a game title.") %>
            </div>
          </div>

          <div class="row">
            <div class="large-4 columns">
              <%= f.label(:city, "City") %>
              <%= f.text_field(:city, :placeholder => "City") %>
            </div>
            <div class="large-4 columns">
              <%= f.label(:state, "State") %>
              <%= f.text_field(:state, :placeholder => "State") %>
            </div>
            <div class="large-4 columns">
              <%= f.label(:zip, "Zip") %>
              <%= f.text_field(:zip, :placeholder => "Zip") %>
            </div>
          </div>
          <p>Optional</p>
           <div class="row">
             <div class="large-12 columns">
               <%= f.label(:player_max, "Max number of players?") %>
               <%= f.text_field(:player_max, :placeholder => "Enter a number") %>
             </div>
           </div>
          <div class="row">
            <div class="large-12 columns">
              <%= f.label(:equipment, "Equipment") %>
              <%= f.text_field(:equipment, :placeholder => "Do players need to bring any equipment?") %>
            </div>
          </div>
          <div class="row">
            <div class="large-12 columns">
              <%= f.submit "Get this game started!", :class => 'button right' %>
              <%= link_to "Back", '#', :class => 'button secondary left back-button' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/games/edit.html.erb
<div class="button-bar">
  <ul class="button-group">
    <li><%= link_to 'View game', @game, :class => 'small button' %></li>
    <li><%= link_to 'Find another game', games_path, :class => 'small button' %></li>
  </ul>
</div>
<div class="large-4 columns large-centered">
  <%= image_tag("logo-mascot.png", :class => 'has-tip tip-bottom', :title => 'The pug in pugwarriors stands for "Pick-up game"', 'data-tooltip' => '') %>
</div>
<h1 class="title">Editing your pick-up game.</h1>
<%= render 'form' %>

app/views/games/index.html.erb
<div id="create-game" class="large-12 columns">
  <div class="row">
    <div class="large-9 columns large-centered">
      <div class="row">
        <h1 class="title">Find games near you</h1>
        <%= form_for :games_filter, :url => '/games/filter' do |f|  %>
          <div class="right">
            <div class="row collapse">
              <div class="small-8 columns">
                <%= f.text_field :zip, :placeholder => "Enter your zip code", :value => @filter %>
              </div>
              <div class="small-4 columns">
                <%= f.submit "Search", :class => "button prefix" %>
              </div>
            </div>
          </div>
        <% end %>
        <div class="left">
          <%= link_to 'View pick-up games on twitter in your area.', '/tweets', :class => 'button' %>
        </div>
      </div>

      <% @games.each do |game| %>
        <div class="row game">
          <div class="game-name-wrapper large-12 columns">
            <% if game.author_handle.present? %>
              <span class="left"><%= image_tag game.author_image %></span>
              <h4><%= link_to game.name, game %></h4>
            <% end %>
          </div>

          <div class="large-12 no-padding small-12 columns">
            <div class="join-wrapper large-3 small-6 columns">
              <% if user_signed_in? %>
                <div id="join-leave-<%= game.id.to_s %>">
                  <% if game.users.present? && game.users.where(:_id => current_user.id).first %>
                    <%= link_to "Leave Game", '/games/' + game.id + '/leave', {:remote => true, :class => 'leave'} %>
                  <% else %>
                    <%= link_to "Join Game", '/games/' + game.id + '/join', {:remote => true, :class => 'join'} %>
                  <% end %>
                </div>
              <% else %>
                <%= link_to "Sign-in to join", '/auth/twitter' %>
              <% end %>
            </div>

            <div class="time-and-location-wrapper large-3 small-6 columns">
              <a class="time-and-location">
                <div class="time-wrapper">
                  <%= game.time %>
                </div>
                <div class="location-wrapper">
                  <p><%= game.location %></p>
                </div>
              </a>
            </div>

            <div class="member-count-wrapper large-3 small-6 columns">
              <div id="member-count-<%= game.id.to_s %>">
                <% if game.users.present? %>
                  <a href="#" class="user-count">
                    <%= game.users.count %>
                    <p>Players</p>
                  </a>
                <% else %>
                  <a href="#" class="user-count">
                    0
                    <p>Players</p>
                  </a>
                <% end %>
              </div>
            </div>

            <div class="game-date-wrapper large-3 small-6 columns">
              <a href="">
                <p><%= game.date.strftime('%B') %></p>
                <%= game.date.strftime('%d') %>
              </a>
            </div>
          </div>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/games/join.js.erb
$('#member-count-<%= @game.id.to_s %>').html('<a href="#" class="user-count"><%= @game.users.count %><p>Players</p></a>');
$('#join-leave-<%= @game.id.to_s %>').html('<%= escape_javascript(link_to "Leave Game", "/games/" + @game.id + "/leave", {:remote => true, :class => 'leave'}) %>');

app/views/games/leave.js.erb
$('#member-count-<%= @game.id.to_s %>').html('<a href="#" class="user-count"><%= @game.users.count if @game.users.present? %><p>Players</p></a>');
$('#join-leave-<%= @game.id.to_s %>').html('<%= escape_javascript(link_to "Join Game", '/games/' + @game.id + '/join', {:remote => true, :class => 'join'}) %>');

app/views/games/new.html.erb
<div class="large-4 small-6 small-centered columns large-centered">
  <%= image_tag("logo-mascot.png", :class => 'has-tip tip-bottom', :title => 'The pug in pugwarriors stands for "Pick-up game"', 'data-tooltip' => '') %>
</div>
<h1 class="title">Create a pick-up game.</h1>
<%= render 'form' %>

app/views/games/show.html.erb
<div id="show-game">
  <div class="game clearfix">
    <div class="game-name-wrapper large-12 columns">
        <span class="left"><%= image_tag @user.image %></span>
        <h4>
          <%= @game.name %>
          <div class="admin-actions right">
            <% if !@game.admin || (@game.admin && current_user && @game.admin == current_user.twitter_id)%>
              <%= link_to 'Edit', edit_game_path(@game), :class => 'small button' %>
            <% end %>
          </div>
        </h4>
    </div>

    <div id="game-content-area" class="large-8 columns">

      <div id="info-panels" class="large-12 no-padding small-12 columns">
        <div class="join-wrapper large-3 small-6 columns">
          <% if user_signed_in? %>
            <div id="join-leave-<%= @game.id.to_s %>">
              <% if @game.users.present? && @game.users.where(:_id => current_user.id).first %>
                <%= link_to "Leave Game", '/games/' + @game.id + '/leave', {:remote => true, :class => 'leave'} %>
              <% else %>
                <%= link_to "Join Game", '/games/' + @game.id + '/join', {:remote => true, :class => 'join'} %>
              <% end %>
            </div>
          <% else %>
            <%= link_to "Sign-in to join", '/auth/twitter' %>
          <% end %>
        </div>

        <div class="time-and-location-wrapper large-3 small-6 columns">
          <a class="time-and-location">
            <div class="time-wrapper">
              <%= @game.time %>
            </div>
            <div class="location-wrapper">
              <p><%= @game.location %></p>
            </div>
          </a>
        </div>

        <div class="member-count-wrapper large-3 small-6 columns">
          <div id="member-count-<%= @game.id.to_s %>">
            <% if @game.users.present? %>
              <a href="#" class="user-count">
                <%= @game.users.count %>
                <p>Players</p>
              </a>
            <% else %>
              <a href="#" class="user-count">
                0
                <p>Players</p>
              </a>
            <% end %>
          </div>
        </div>

        <div class="game-date-wrapper large-3 small-6 columns">
          <a href="">
            <p><%= @game.date.strftime('%B') %></p>
            <%= @game.date.strftime('%d') %>
          </a>
        </div>
      </div>
      <div class="large-12 columns">
        <div id="map-canvas"></div>
      </div>

    </div>

    <div id="comment-column" class="large-4 columns">
      <% if user_signed_in? %>
        <%= form_for(@comment, :remote => true, :method => "post") do |f| %>
          <% if @comment.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
              <ul>
                <% @comment.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
          <% end %>
          <div class="row post-input-wrapper">
            <div class="large-10 columns">
              <%= f.text_field(:comment, :placeholder => "Write a comment") %>
              <%= f.hidden_field(:game_id, :value => @game.id) %>
            </div>
            <div class="large-2 columns">
              <%= f.submit "Post", :class => 'button secondary right' %>
            </div>
          </div>
        <% end %>
      <% else %>
        <div class="row post-input-wrapper">
          <%= link_to "Sign-in to comment", '/auth/twitter', :class => 'button large-12 columns' %>
        </div>
      <% end %>
      <ul class="comment-list" id="comment-list">
        <%= render @comments %>
      </ul>
    </div>
  </div>
</div>