config/routes.rb
require 'resque/server'

Pugwarriors::Application.routes.draw do
  resources :authentications
  resources :games
  resources :tweets
  resources :comments

  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  if ENV["RESQUE_WEB_PASS"]
    Resque::Server.use Rack::Auth::Basic do |username, password|
      password = ENV["RESQUE_WEB_PASS"]
    end
  end

  mount Resque::Server.new, :at => "/resque"

  mount Foundation::Icons::Rails::Engine => '/fi'
  match '/users/signout' => 'sessions#destroy', :as => :signout
  match '/games/:id/join' => 'games#join'
  match '/games/:id/leave' => 'games#leave'
  match '/games/:id/admin' => 'games#admin'
  match '/users/:id/games' => 'users#games'
  match '/games/:id/comments' => 'comments#create'
  match '/games/filter' => 'games#filter'
  match '/tweets/filter' => 'tweets#filter'
  match '/application/viewed_notification' => 'application#viewed_notification'
  match '/tweets/get_new_tweets' => 'tweets#get_new_tweets'
  match '/auth/:provider/callback' => 'authentications#create'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box">
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#"><%= link_to image_tag('logo.png'), '/' %></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li>
          <%= link_to 'Create a game', new_game_path %>
        </li>
        <li>
          <%= link_to 'Find a game', games_path %>
        </li>
        <li>
          <%= render_cell :notifications, :show, :user => current_user %>
        </li>

        <% if !user_signed_in? %>
          <li><%= link_to 'Sign in with twitter', '/auth/twitter' %></li>
        <% end %>

        <% if user_signed_in? %>
        <li class="has-dropdown"><%= image_tag current_user.image, :title => current_user.name, :class => 'mini_user_profile_image' %>

          <ul class="dropdown">
            <li><%= link_to 'Edit account', edit_user_registration_path %></li>
            <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
          </ul>
        </li>
        <% end %>
      </ul>
    </section>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "pugwarriors.com" %></title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false"></script>
  <%= google_webfonts_link_tag "Raleway" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %> <%= action_name %>">

  <header>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
  </header>
  <div id="container">
    <div id="main" role="main">
      <%= yield %>
    </div>
  </div> <!--! end of #container -->
  <%= javascript_include_tag "application" %>


  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-44926770-1', 'pugwarriors.com');
    ga('send', 'pageview');

  </script>
</body>
</html>